name: OnPullRequest

on:
  pull_request:

permissions: read-all

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.step1.outputs.runner }}
    steps:
      - name: Check repository
        id: step1
        run: |
          if [ ${{ github.repository }} == 'intel/trustauthority-kbs' ]; then
            echo "runner=ubuntu-latest" >> $GITHUB_OUTPUT
          else
            echo "runner=self-hosted" >> $GITHUB_OUTPUT
          fi

  security-file-check:
    needs: [setup]
    runs-on: ${{ needs.setup.outputs.runner }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - name: Check Security.md file
        run: |
          if [ ! -f ./Security.md ]; then
            echo "Security.md file is missing"
            exit 1
          fi

  build-test-scan:
    needs: [setup]
    runs-on: ${{ needs.setup.outputs.runner }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: "1.22.3"

      - name: Style Checker
        run: |
          gofmt -l .
          if [[ $(gofmt -l . | wc -l) -gt 0 ]]; then
             echo "Atleast 1 file need formatting"
             exit 1
          fi

      - name: Unit Test Coverage
        run: |
          COVERAGE=$(make test-coverage | grep 'total' | awk '{print $3}' | awk -F. '{print $1}')
          echo "Unit test coverage is - $COVERAGE%"
          if [[ $COVERAGE -lt 80 ]]; then
            echo "Unit test coverage must be above 80% "
            exit 1
          fi
